version: '3.9'
services:
  readme.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: 'readme.notify.fakesmtp'
    hostname: 'readme.notify.fakesmtp'
    ports:
      - '8025:8025'
      - '1085:8080'
